<a href="https://colab.research.google.com/github/KarynaSam/Python-DS/blob/main/HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1)Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.


In [1]:
import numpy as np

a = np.arange(10)

print(a)

[0 1 2 3 4 5 6 7 8 9]


2) Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.


In [2]:
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3) Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [3]:
a = np.random.randint(1, 10, (5,5), dtype=int)
print(a)

[[2 2 2 1 9]
 [3 6 6 7 2]
 [2 8 1 7 9]
 [4 7 1 8 3]
 [6 6 5 6 8]]


4)Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [4]:
a = np.random.random((4,4))
print(a)

[[0.44459756 0.01691315 0.42509231 0.26351558]
 [0.46997718 0.3289777  0.91261632 0.92085217]
 [0.65368748 0.73674322 0.87736415 0.09702992]
 [0.15894884 0.27410829 0.27343308 0.36511223]]


5)Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.


In [5]:
a = np.random.randint(1, 10, (5,), dtype = int)
b = np.random.randint(1, 10, (5,), dtype = int)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)

[9 2 2 5 9]
[5 8 2 3 8]
[14 10  4  8 17]
[ 4 -6  0  2  1]
[45 16  4 15 72]


6)Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [6]:
a = np.random.randint(1, 10, (5,), dtype = int)
b = np.random.randint(1, 10, (5,), dtype = int)

print(a.dot(b))

105


7)Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [8]:
a = np.random.randint(1, 10, (2,2), dtype = int)
b = np.random.randint(1, 10, (2,3), dtype = int)

print(a.dot(b))

[[46 40 54]
 [37 34 39]]


8)Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [7]:
a = np.random.randint(1, 10, (3,3), dtype = int)
print(np.linalg.inv(a))

[[ 0.42982456  0.25438596 -0.54385965]
 [-0.04385965  0.09649123  0.03508772]
 [-0.03508772 -0.12280702  0.22807018]]


9)Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [9]:
a = np.random.random((4,4))
print(a.T)

[[0.6017315  0.77921891 0.03183514 0.99063122]
 [0.75258039 0.01356832 0.68556874 0.89999078]
 [0.17296765 0.50184298 0.78294176 0.39239397]
 [0.63321619 0.16539145 0.9804528  0.41000021]]


10)Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [10]:
a = np.random.randint(1, 10, (3,4), dtype=int)
b = np.random.randint(1, 10, (4), dtype=int)

print(a@b)

[185 129 183]


11)Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [11]:
a = np.random.randint(1, 10, (2,3), dtype=int)
b = np.random.randint(1, 10, (3), dtype=int)

print(a@b)

[111 120]


12)Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [12]:
a = np.random.randint(1, 10, (2,2), dtype=int)
b = np.random.randint(1, 10, (2,2), dtype=int)

print(a*b)

[[36 54]
 [ 2 49]]


13)Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [13]:
a = np.random.randint(1, 10, (2,2), dtype=int)
b = np.random.randint(1, 10, (2,2), dtype=int)

print(a@b)

[[33 91]
 [44 63]]


14)Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [14]:
a = np.random.randint(1, 100, (5,5), dtype=int)
print(np.sum(a))

1176


15)Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [15]:
a = np.random.randint(1, 10, (4,4), dtype=int)
b = np.random.randint(1, 10, (4,4), dtype=int)
print(np.subtract(a,b))

[[ 0  0  0  2]
 [-4 -3  7  8]
 [-7 -3  3 -5]
 [-5  5 -4  6]]


16)Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
a = np.random.random((3,3))
b = np.array([np.sum(a[:1]), np.sum(a[1:2]), np.sum(a[2:])])
c = np.sum(a, axis=1)
print(b)
print(c)

17)Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [16]:
a = np.random.randint(1, 10, (3,4), dtype=int)
print(np.square(a))
print(np.power(a, 2))

[[ 1 81 49 49]
 [ 9 81  1  9]
 [ 1 49 25 81]]
[[ 1 81 49 49]
 [ 9 81  1  9]
 [ 1 49 25 81]]


18)Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [18]:
a = np.random.randint(1, 50, (4), dtype=int)
print(np.sqrt(a))
print(np.power(a, 1/2))

[6.08276253 5.74456265 2.44948974 2.64575131]
[6.08276253 5.74456265 2.44948974 2.64575131]
