<a href="https://colab.research.google.com/github/KarynaSam/Python-DS/blob/main/Model_balance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from datetime import datetime

In [ ]:
xf = pd.read_csv("Balance model data extended event.csv", delimiter=";")
xf.head()

dt  Sum of outs  trans_count  Weekday  Is holiday  Event importance
0  1/1/2023  180 959 499          534        6           1                 9
1  1/2/2023  397 113 111          686        0           1                 9
2  1/3/2023  277 962 729          652        1           0                 9
3  1/4/2023  272 484 769          694        2           0                 9
4  1/5/2023  268 994 831          628        3           0                 9

In [ ]:
yf = pd.read_csv("Y Balances.csv", delimiter=";")
yf.head()

dt      Balance
0  1/1/2023  182 769 000
1  1/2/2023  401 084 000
2  1/3/2023  280 742 000
3  1/4/2023  275 210 000
4  1/5/2023  271 685 000

In [ ]:
x_train = np.array(xf)
y_train = np.array(yf)
print(f"x_train = {x_train}")
print(f"y_train = {y_train}")

x_train = [['1/1/2023' '180 959 499' 534 6 1 9]
 ['1/2/2023' '397 113 111' 686 0 1 9]
 ['1/3/2023' '277 962 729' 652 1 0 9]
 ...
 ['11/28/2023' '187 209 430' 173 1 0 0]
 ['11/29/2023' '174 834 582' 146 2 0 0]
 ['11/30/2023' '128 503 016' 152 3 0 0]]
y_train = [['1/1/2023' '182 769 000']
 ['1/2/2023' '401 084 000']
 ['1/3/2023' '280 742 000']
 ['1/4/2023' '275 210 000']
 ['1/5/2023' '271 685 000']
 ['1/6/2023' '367 288 000']
 ['1/7/2023' '302 683 000']
 ['1/8/2023' '232 638 000']
 ['1/9/2023' '330 935 000']
 ['1/10/2023' '299 741 000']
 ['1/11/2023' '233 735 000']
 ['1/12/2023' '233 937 000']
 ['1/13/2023' '281 558 000']
 ['1/14/2023' '211 763 000']
 ['1/15/2023' '238 228 000']
 ['1/16/2023' '254 479 000']
 ['1/17/2023' '310 430 000']
 ['1/18/2023' '277 365 000']
 ['1/19/2023' '258 003 000']
 ['1/20/2023' '309 042 000']
 ['1/21/2023' '265 401 000']
 ['1/22/2023' '317 145 000']
 ['1/23/2023' '281 795 000']
 ['1/24/2023' '210 662 000']
 ['1/25/2023' '210 483 000']
 ['1/26/2023' '207 884 0

In [ ]:
a = []
with open('Balance model data extended event.csv', 'r') as f:
  b = f.readlines()
  a.append(b[0].split(';'))
  for i in b[1:]:
    parts = i.split(';')
    a.append([datetime.strptime(parts[0],'%m/%d/%Y').strftime('%j'), parts[1].replace(' ', ''), *parts[2:]])
with open('Balance model data float.csv', 'w') as f:
  for i in a:
    f.write(';'.join(i))


In [ ]:
b = []
with open('Y Balances.csv', 'r') as f:
  c = f.readlines()
  b.append(c[0].split(';'))
  for i in c[1:]:
    parts = i.split(';')
    b.append([datetime.strptime(parts[0],'%m/%d/%Y').strftime('%j'), parts[1].replace(' ', '')])
with open('Y Balances data float.csv', 'w') as f:
  for i in b:
    f.write(';'.join(i))

In [ ]:
x1f = pd.read_csv("Balance model data float.csv", delimiter=";")
y1f = pd.read_csv("Y Balances data float.csv", delimiter=";")
x1f.head()
y1f.head()


Balance
0  182769000
1  401084000
2  280742000
3  275210000
4  271685000

In [ ]:
x1_train = np.array(x1f)
y1_train = np.array(y1f)
print(f"x1_train = {x1_train}")
print(f"y1_train = {y1_train}")

x1_train = [[        1 180959499       534         6         1         9]
 [        2 397113111       686         0         1         9]
 [        3 277962729       652         1         0         9]
 ...
 [      332 187209430       173         1         0         0]
 [      333 174834582       146         2         0         0]
 [      334 128503016       152         3         0         0]]
y1_train = [[182769000]
 [401084000]
 [280742000]
 [275210000]
 [271685000]
 [367288000]
 [302683000]
 [232638000]
 [330935000]
 [299741000]
 [233735000]
 [233937000]
 [281558000]
 [211763000]
 [238228000]
 [254479000]
 [310430000]
 [277365000]
 [258003000]
 [309042000]
 [265401000]
 [317145000]
 [281795000]
 [210662000]
 [210483000]
 [207884000]
 [260975000]
 [246766000]
 [202461000]
 [298214000]
 [281663000]
 [233478000]
 [318864000]
 [278701000]
 [300238000]
 [265797000]
 [278100000]
 [281909000]
 [382315000]
 [332770000]
 [317951000]
 [252466000]
 [369762000]
 [333727000]
 [346231000]
 [2831300

In [ ]:
linear_model = LinearRegression()
linear_model.fit(x1_train, y1_train)

LinearRegression()

In [ ]:
b = linear_model.intercept_
w = linear_model.coef_
print(f"w = {w:}, b = {b:0.2f}")

TypeError: ignored

In [ ]:
print(f"Prediction on training set:\n {linear_model.predict(x1_train)[:6]}" )
print(f"prediction using w,b:\n {(x1_train @ w + b)}")
print(f"Target values \n {y1_train[:6]}")

x = np.array([213, 363000000,750, 4, 1, 9]).reshape(-1,6)
x_predict = linear_model.predict(x)[0]
print(f" prediction = ${x_predict:0.2f}")

Prediction on training set:
 [[1.82769177e+08]
 [4.01084183e+08]
 [2.80742286e+08]
 [2.75209579e+08]
 [2.71684713e+08]
 [3.67288116e+08]]


ValueError: ignored